apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-ouoj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:9588fbc85b4dcdc05631f8332d32f928e087217451e393c23687960d1a0f209c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
