apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-ouoj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:e7b70faf98dbfe7d972093edd76bdf1fba1324bace362c5ab853ca59462e06b8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
